sudo: required
services:
  - docker

before_install:
  - docker build -t salehmajeed/docker-practice -f Dockerfile .


script:
  - docker run -e CI=TRUE salehmajeed/docker-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-practice"
  env: "Docker-env"
  bucket_name: "s3-bucket-url"
  bucket_path: "docker-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"