version: '3'
services:
  web:
    build:
      context:  /home/pc/Desktop/learning/DevOps/docker-and-kubernetes-the-complete-guide/5. production grade workflow/frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context:  /home/pc/Desktop/learning/DevOps/docker-and-kubernetes-the-complete-guide/5. production grade workflow/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]